function config = config()
%% generate the config

config = struct(                        ...
    'maxpid'          , 65,             ...
    'maxpic_id'       , 21,             ...
    'pic_width'       , 100,            ...
    'pic_height'      , 100,            ...
    'id_for_train'    , [7, 10, 19]     );
